Controllers/ActorsController.cs
using eTickets.Data;
using eTickets.Data.DTOs;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class ActorsController : Controller
	{
		private readonly IActorsService _service;
        public ActorsController(IActorsService service)
        {
			_service = service;
        }

        public async Task<IActionResult> Index()
		{
			var Actors = await _service.GetAllAsync();
			return View(Actors);
		}

        public IActionResult Create()
        {
            return View();
        }

		[HttpPost]
		public IActionResult Create(ActorDTO actordto)
		{
			if(!ModelState.IsValid)
			{
				return View(actordto);
			}

			var actor = new Actor()
			{
				ProfilePictureURL = actordto.ProfilePictureURL,
				FullName = actordto.FullName,
				Bio = actordto.Bio
			};
			_service.AddAsync(actor);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Details(int id)
		{
			var actor = await _service.GetByIdAsync(id);

			if(actor == null)
			{
				return View("NotFound");
			}
			return View(actor);
		}

		public async Task<IActionResult> Edit(int id)
		{
			if(id  <= 0)
				return View("NotFound");

			var actor = await _service.GetByIdAsync(id);

			if (actor == null)
				return View("NotFound");

			return View(actor);
		}

		[HttpPost]
		public async Task<IActionResult> Edit([FromRoute]int id,ActorDTO actordto)
		{
			if (id <= 0)
				return View("NotFound");

			if (!ModelState.IsValid)
				return View(actordto);

			var actor = new Actor
			{
				ID = id,
				ProfilePictureURL = actordto.ProfilePictureURL,
				FullName = actordto.FullName,
				Bio = actordto.Bio
			};
			await  _service.UpdateAsync(actor);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Delete(int id)
		{
			if (id <= 0)
				return View("NotFound");

			var actor = await _service.GetByIdAsync(id);

			if (actor == null)
				return View("NotFound");

			return View(actor);
		}

		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed([FromRoute] int id)
		{
			if (id <= 0)
				return View("NotFound");

			var actor = await _service.GetByIdAsync(id);

			if (actor == null)
				return View("NotFound");

			 await _service.DeleteAsync(actor);
			return RedirectToAction(nameof(Index));
		}
	}
}

Controllers/CinemasController.cs
using eTickets.Data;
using eTickets.Data.DTOs;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class CinemasController : Controller
	{
		private readonly ICinemasService _service;
		public CinemasController(ICinemasService service)
		{
			_service = service;
		}
		public async Task<IActionResult> Index()
		{
			var cinemas = await _service.GetAllAsync();
			return View(cinemas);
		}
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(CinemaDTO cinemadto)
		{
			if (!ModelState.IsValid)
			{
				return View(cinemadto);
			}

			var cinema = new Cinema()
			{
				Logo = cinemadto.Logo,
				Name = cinemadto.Name,
				Description = cinemadto.Description
			};
			_service.AddAsync(cinema);
			return RedirectToAction(nameof(Index));
		}
		public async Task<IActionResult> Details(int id)
		{
			var cinema = await _service.GetByIdAsync(id);

			if (cinema == null)
			{
				return View("NotFound");
			}
			return View(cinema);
		}

		public async Task<IActionResult> Edit(int id)
		{
			if (id <= 0)
				return View("NotFound");

			var cinema = await _service.GetByIdAsync(id);

			if (cinema == null)
				return View("NotFound");

			return View(cinema);
		}

		[HttpPost]
		public async Task<IActionResult> Edit([FromRoute] int id, CinemaDTO cinemadto)
		{
			if (id <= 0)
				return View("NotFound");

			if (!ModelState.IsValid)
				return View(cinemadto);

			var cinema = new Cinema
			{
				ID = id,
				Logo = cinemadto.Logo,
				Name = cinemadto.Name,
				Description = cinemadto.Description
			};
			await _service.UpdateAsync(cinema);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Delete(int id)
		{
			if (id <= 0)
				return View("NotFound");

			var cinema = await _service.GetByIdAsync(id);

			if (cinema == null)
				return View("NotFound");

			return View(cinema);
		}

		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed([FromRoute] int id)
		{
			if (id <= 0)
				return View("NotFound");

			var cinema = await _service.GetByIdAsync(id);

			if (cinema == null)
				return View("NotFound");

			await _service.DeleteAsync(cinema);
			return RedirectToAction(nameof(Index));
		}
	}
}

Controllers/MoviesController.cs
using eTickets.Data;
using eTickets.Data.DTOs;
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class MoviesController : Controller
	{
		private readonly IMoviesService _service;
		public MoviesController(IMoviesService service)
		{
			_service = service;
		}
		public async Task<IActionResult> Index()
		{
			var movies = await _service.GetAllAsync(n => n.Cinema);
			return View(movies);
		}

		public async Task<IActionResult> Filter(string searchString)
		{
			var movies = await _service.GetAllAsync(n => n.Cinema);

			if(!string.IsNullOrEmpty(searchString))
			{
				var filteredResult = movies.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
				return View("Index", filteredResult);
			}

			return View("Index", movies);
		}

		public async Task<IActionResult> Details(int id)
		{
			var movie = await _service.GetMovieByIdAsync(id);

			if (movie == null)
			{
				return View("NotFound");
			}

			return View(movie);
		}

        public async Task<IActionResult> Create()
        {
			var movieDropDownData = await _service.GetMovieDropDownsValues();

			ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "ID", "Name");
			ViewBag.Producers = new SelectList(movieDropDownData.Producers, "ID", "FullName");
			ViewBag.Actors = new SelectList(movieDropDownData.Actors, "ID", "FullName");

            return View();
        }

		[HttpPost]
		public async Task<IActionResult> Create(MovieVM movieVM)
		{
			if (!ModelState.IsValid)
			{
                var movieDropDownData = await _service.GetMovieDropDownsValues();

                ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "ID", "Name");
                ViewBag.Producers = new SelectList(movieDropDownData.Producers, "ID", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownData.Actors, "ID", "FullName");
            }

			await _service.AddMovieAsync(movieVM);

			return RedirectToAction(nameof(Index));
		}

        public async Task<IActionResult> Edit(int id)
        {
			var movie = await _service.GetMovieByIdAsync(id);

			if(movie == null)
				return View("NotFound");

			var response = new MovieVM()
			{
				ID = movie.ID,
				Name = movie.Name,
				Description = movie.Description,
				Price = movie.Price,
				StartDate = movie.StartDate,
				EndDate = movie.EndDate,
				ImageURL = movie.ImageURL,
				CinemaID = movie.CinemaID,
				ProdcerID = movie.ProdcerID,
				MovieCategory = movie.MovieCategory,
				ActorIDs = movie.Actors_Movies.Select(n => n.ActorID).ToList(),
			};

            var movieDropDownData = await _service.GetMovieDropDownsValues();

            ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "ID", "Name");
            ViewBag.Producers = new SelectList(movieDropDownData.Producers, "ID", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownData.Actors, "ID", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, MovieVM movieVM)
        {
			if (id != movieVM.ID)
				return View("NotFound");

            if (!ModelState.IsValid)
            {
                var movieDropDownData = await _service.GetMovieDropDownsValues();

                ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "ID", "Name");
                ViewBag.Producers = new SelectList(movieDropDownData.Producers, "ID", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownData.Actors, "ID", "FullName");
				return View(movieVM);
            }

            await _service.UpdateMovieAsync(movieVM);

            return RedirectToAction(nameof(Index));
        }
	}
}

Controllers/OrdersController.cs
using eTickets.Data.Cart;
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace eTickets.Controllers
{
	public class OrdersController : Controller
	{
		private readonly IMoviesService _moviesService;
		private readonly IOrderService _orderService;
		private readonly ShoppingCart _shoppingCart;
        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrderService orderService)
        {
			_moviesService = moviesService;
			_shoppingCart = shoppingCart;
			_orderService = orderService;
        }

		public async Task<IActionResult> Index()
		{
			string userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string userRole = User.FindFirstValue(ClaimTypes.Role);

			var orders = await _orderService.GetOrdersByUserIDAndRoleAsync(userID,userRole);

			return View(orders);
		}


        public IActionResult ShoppingCart()
		{
			var items = _shoppingCart.GetShoppingCartItems();

			_shoppingCart.ShoppingCartItems = items;

			var response = new ShoppingCartVM()
			{
				ShoppingCart = _shoppingCart,
				ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
			};
			return View(response);
		}
		
		public async Task<IActionResult> AddItemToShoppingCart(int id)
		{
			var item = await _moviesService.GetMovieByIdAsync(id);

			if(item != null)
			{
				_shoppingCart.AddItemToCart(item);
			}
			return RedirectToAction(nameof(ShoppingCart));
		}

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

		public async Task<IActionResult> CompleteOrder()
		{
			var items =  _shoppingCart.GetShoppingCartItems();

			string userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string userEmailAdress = User.FindFirstValue(ClaimTypes.Email); ;

			await _orderService.StoreOrderAsync(items, userID, userEmailAdress);
			await _shoppingCart.ClearShoppingCartAsync();

			return View("OrderCompleted");
		}

	}
}

Views/Shared/NotFound.cshtml
<div class="row">
	<div class="col-md-6 offset-3">
		<h1 class="text-danger"> Not Found!!!!!!!</h1>
		<a asp-controller="Movies" asp-action="Index" class="mt-3 btn btn-outline-secondary">Movies</a>
	</div>
</div>

Views/Shared/_CreateItem.cshtml
@model string
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
	<div class="text-white" style="position:fixed; right: 25px; bottom:25px;">
		<a asp-controller="@Model" asp-action="Create" class="btn btn-success">
			<i class="bi bi-plus-circle"></i> Add new
		</a>
	</div>
}

Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> userManager;

@if(!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log In
    </a>

    <span style="padding:5px;"></span>
    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{

    @* user profile section *@
    <div class="drop-down">
        <button class="btn btn-outline-success  dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-badge"></i> @userManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index"><i class="bi bi-list"></i> Orders</a>
            </li>
            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users"><i class="bi bi-people"></i> Users</a>
                </li>
            }
        </ul>
    </div>

    <span style="padding:5px;"></span>

    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-right"></i> Log out
        </button>
    </form>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eTickets.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index"><i class="badge-info bi-film"></i> Movies</a>
                        </li>
                        
                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                    <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                </div>

                            </li>
                        }
                    </ul>

                    <form class="form-inline my-2 my-lg-0 d-flex" asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                    @await Html.PartialAsync("_Identity")

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - eTickets
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>