Controllers/ActorsController.cs
using eTickets.Data;
using eTickets.Data.DTOs;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class ActorsController : Controller
	{
		private readonly IActorsService _service;
        public ActorsController(IActorsService service)
        {
			_service = service;
        }

        public async Task<IActionResult> Index()
		{
			var Actors = await _service.GetAllAsync();
			return View(Actors);
		}

        public IActionResult Create()
        {
            return View();
        }

		[HttpPost]
		public IActionResult Create(ActorDTO actordto)
		{
			if(!ModelState.IsValid)
			{
				return View(actordto);
			}

			var actor = new Actor()
			{
				ProfilePictureURL = actordto.ProfilePictureURL,
				FullName = actordto.FullName,
				Bio = actordto.Bio
			};
			_service.AddAsync(actor);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Details(int id)
		{
			var actor = await _service.GetByIdAsync(id);

			if(actor == null)
			{
				return View("NotFound");
			}
			return View(actor);
		}

		public async Task<IActionResult> Edit(int id)
		{
			if(id  <= 0)
				return View("NotFound");

			var actor = await _service.GetByIdAsync(id);

			if (actor == null)
				return View("NotFound");

			return View(actor);
		}

		[HttpPost]
		public async Task<IActionResult> Edit([FromRoute]int id,ActorDTO actordto)
		{
			if (id <= 0)
				return View("NotFound");

			if (!ModelState.IsValid)
				return View(actordto);

			var actor = new Actor
			{
				ID = id,
				ProfilePictureURL = actordto.ProfilePictureURL,
				FullName = actordto.FullName,
				Bio = actordto.Bio
			};
			await  _service.UpdateAsync(actor);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Delete(int id)
		{
			if (id <= 0)
				return View("NotFound");

			var actor = await _service.GetByIdAsync(id);

			if (actor == null)
				return View("NotFound");

			return View(actor);
		}

		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed([FromRoute] int id)
		{
			if (id <= 0)
				return View("NotFound");

			var actor = await _service.GetByIdAsync(id);

			if (actor == null)
				return View("NotFound");

			 await _service.DeleteAsync(actor);
			return RedirectToAction(nameof(Index));
		}
	}
}

Controllers/CinemasController.cs
using eTickets.Data;
using eTickets.Data.DTOs;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class CinemasController : Controller
	{
		private readonly ICinemasService _service;
		public CinemasController(ICinemasService service)
		{
			_service = service;
		}
		public async Task<IActionResult> Index()
		{
			var cinemas = await _service.GetAllAsync();
			return View(cinemas);
		}
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(CinemaDTO cinemadto)
		{
			if (!ModelState.IsValid)
			{
				return View(cinemadto);
			}

			var cinema = new Cinema()
			{
				Logo = cinemadto.Logo,
				Name = cinemadto.Name,
				Description = cinemadto.Description
			};
			_service.AddAsync(cinema);
			return RedirectToAction(nameof(Index));
		}
		public async Task<IActionResult> Details(int id)
		{
			var cinema = await _service.GetByIdAsync(id);

			if (cinema == null)
			{
				return View("NotFound");
			}
			return View(cinema);
		}

		public async Task<IActionResult> Edit(int id)
		{
			if (id <= 0)
				return View("NotFound");

			var cinema = await _service.GetByIdAsync(id);

			if (cinema == null)
				return View("NotFound");

			return View(cinema);
		}

		[HttpPost]
		public async Task<IActionResult> Edit([FromRoute] int id, CinemaDTO cinemadto)
		{
			if (id <= 0)
				return View("NotFound");

			if (!ModelState.IsValid)
				return View(cinemadto);

			var cinema = new Cinema
			{
				ID = id,
				Logo = cinemadto.Logo,
				Name = cinemadto.Name,
				Description = cinemadto.Description
			};
			await _service.UpdateAsync(cinema);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Delete(int id)
		{
			if (id <= 0)
				return View("NotFound");

			var cinema = await _service.GetByIdAsync(id);

			if (cinema == null)
				return View("NotFound");

			return View(cinema);
		}

		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed([FromRoute] int id)
		{
			if (id <= 0)
				return View("NotFound");

			var cinema = await _service.GetByIdAsync(id);

			if (cinema == null)
				return View("NotFound");

			await _service.DeleteAsync(cinema);
			return RedirectToAction(nameof(Index));
		}
	}
}

Controllers/MoviesController.cs
using eTickets.Data;
using eTickets.Data.DTOs;
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class MoviesController : Controller
	{
		private readonly IMoviesService _service;
		public MoviesController(IMoviesService service)
		{
			_service = service;
		}
		public async Task<IActionResult> Index()
		{
			var movies = await _service.GetAllAsync(n => n.Cinema);
			return View(movies);
		}

		public async Task<IActionResult> Filter(string searchString)
		{
			var movies = await _service.GetAllAsync(n => n.Cinema);

			if(!string.IsNullOrEmpty(searchString))
			{
				var filteredResult = movies.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
				return View("Index", filteredResult);
			}

			return View("Index", movies);
		}

		public async Task<IActionResult> Details(int id)
		{
			var movie = await _service.GetMovieByIdAsync(id);

			if (movie == null)
			{
				return View("NotFound");
			}

			return View(movie);
		}

        public async Task<IActionResult> Create()
        {
			var movieDropDownData = await _service.GetMovieDropDownsValues();

			ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "ID", "Name");
			ViewBag.Producers = new SelectList(movieDropDownData.Producers, "ID", "FullName");
			ViewBag.Actors = new SelectList(movieDropDownData.Actors, "ID", "FullName");

            return View();
        }

		[HttpPost]
		public async Task<IActionResult> Create(MovieVM movieVM)
		{
			if (!ModelState.IsValid)
			{
                var movieDropDownData = await _service.GetMovieDropDownsValues();

                ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "ID", "Name");
                ViewBag.Producers = new SelectList(movieDropDownData.Producers, "ID", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownData.Actors, "ID", "FullName");
            }

			await _service.AddMovieAsync(movieVM);

			return RedirectToAction(nameof(Index));
		}

        public async Task<IActionResult> Edit(int id)
        {
			var movie = await _service.GetMovieByIdAsync(id);

			if(movie == null)
				return View("NotFound");

			var response = new MovieVM()
			{
				ID = movie.ID,
				Name = movie.Name,
				Description = movie.Description,
				Price = movie.Price,
				StartDate = movie.StartDate,
				EndDate = movie.EndDate,
				ImageURL = movie.ImageURL,
				CinemaID = movie.CinemaID,
				ProdcerID = movie.ProdcerID,
				MovieCategory = movie.MovieCategory,
				ActorIDs = movie.Actors_Movies.Select(n => n.ActorID).ToList(),
			};

            var movieDropDownData = await _service.GetMovieDropDownsValues();

            ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "ID", "Name");
            ViewBag.Producers = new SelectList(movieDropDownData.Producers, "ID", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownData.Actors, "ID", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, MovieVM movieVM)
        {
			if (id != movieVM.ID)
				return View("NotFound");

            if (!ModelState.IsValid)
            {
                var movieDropDownData = await _service.GetMovieDropDownsValues();

                ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "ID", "Name");
                ViewBag.Producers = new SelectList(movieDropDownData.Producers, "ID", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownData.Actors, "ID", "FullName");
				return View(movieVM);
            }

            await _service.UpdateMovieAsync(movieVM);

            return RedirectToAction(nameof(Index));
        }
	}
}

Controllers/OrdersController.cs
using eTickets.Data.Cart;
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace eTickets.Controllers
{
	public class OrdersController : Controller
	{
		private readonly IMoviesService _moviesService;
		private readonly IOrderService _orderService;
		private readonly ShoppingCart _shoppingCart;
        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrderService orderService)
        {
			_moviesService = moviesService;
			_shoppingCart = shoppingCart;
			_orderService = orderService;
        }

		public async Task<IActionResult> Index()
		{
			string userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string userRole = User.FindFirstValue(ClaimTypes.Role);

			var orders = await _orderService.GetOrdersByUserIDAndRoleAsync(userID,userRole);

			return View(orders);
		}


        public IActionResult ShoppingCart()
		{
			var items = _shoppingCart.GetShoppingCartItems();

			_shoppingCart.ShoppingCartItems = items;

			var response = new ShoppingCartVM()
			{
				ShoppingCart = _shoppingCart,
				ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
			};
			return View(response);
		}
		
		public async Task<IActionResult> AddItemToShoppingCart(int id)
		{
			var item = await _moviesService.GetMovieByIdAsync(id);

			if(item != null)
			{
				_shoppingCart.AddItemToCart(item);
			}
			return RedirectToAction(nameof(ShoppingCart));
		}

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

		public async Task<IActionResult> CompleteOrder()
		{
			var items =  _shoppingCart.GetShoppingCartItems();

			string userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string userEmailAdress = User.FindFirstValue(ClaimTypes.Email); ;

			await _orderService.StoreOrderAsync(items, userID, userEmailAdress);
			await _shoppingCart.ClearShoppingCartAsync();

			return View("OrderCompleted");
		}

	}
}

Controllers/ProducersController.cs
using eTickets.Data;
using eTickets.Data.DTOs;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class ProducersController : Controller
	{
		private readonly IProducersService _service;
		public ProducersController(IProducersService service)
		{
			_service = service;
		}
		public async Task<IActionResult> Index()
		{
			var producers = await _service.GetAllAsync();
			return View(producers);
		}

		public async Task<IActionResult> Details(int id)
		{
			var producer = await _service.GetByIdAsync(id);

			if (producer == null)
			{
				return View("NotFound");
			}
			return View(producer);
		}

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(ProducerDTO producerdto)
		{
			if (!ModelState.IsValid)
			{
				return View(producerdto);
			}

			var producer = new Producer()
			{
				ProfilePictureURL = producerdto.ProfilePictureURL,
				FullName = producerdto.FullName,
				Bio = producerdto.Bio
			};
			await _service.AddAsync(producer);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Edit(int id)
		{
			if (id <= 0)
				return View("NotFound");

			var producer = await _service.GetByIdAsync(id);

			if (producer == null)
				return View("NotFound");

			return View(producer);
		}

		[HttpPost]
		public async Task<IActionResult> Edit([FromRoute] int id, ProducerDTO producerdto)
		{
			if (id <= 0)
				return View("NotFound");

			if (!ModelState.IsValid)
				return View(producerdto);

			var producer = new Producer
			{
				ID = id,
				ProfilePictureURL = producerdto.ProfilePictureURL,
				FullName = producerdto.FullName,
				Bio = producerdto.Bio
			};
			await _service.UpdateAsync(producer);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Delete(int id)
		{
			if (id <= 0)
				return View("NotFound");

			var producer = await _service.GetByIdAsync(id);

			if (producer == null)
				return View("NotFound");

			return View(producer);
		}

		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed([FromRoute] int id)
		{
			if (id <= 0)
				return View("NotFound");

			var producer = await _service.GetByIdAsync(id);

			if (producer == null)
				return View("NotFound");

			await _service.DeleteAsync(producer);
			return RedirectToAction(nameof(Index));
		}
	}
}

Views/Movies/Create - Copy.cshtml
@using eTickets.Data.DTOs;
@using eTickets.Data.Enum;
@using eTickets.Data.ViewModels

@model MovieVM


@{
	ViewData["Tittle"] = "Create a new movie";
}

<div class="row">
	<div class="col-md-8 offset-2">
		<p>
			<h4>Create a new movie</h4>
		</p>
	</div>
	<div class="row">
		<div class="col-md-8 offset-2">
			<form asp-action="Create">
				<div class="row">
					<div class="col-md-6">
						<div class="mb-2">
							<label asp-for="Name" class="control-label"></label>
							<input asp-for="Name" class="form-control"/>
							<span asp-validation-for="Name" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="StartDate" class="control-label"></label>
							<input asp-for="StartDate" type="date" class="form-control" />
							<span asp-validation-for="StartDate" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="EndDate" class="control-label"></label>
							<input asp-for="EndDate" type="date" class="form-control" />
							<span asp-validation-for="EndDate" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="Price" class="control-label"></label>
							<input asp-for="Price" type="number" class="form-control" />
							<span asp-validation-for="Price" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="ImageURL" class="control-label"></label>
							<input asp-for="ImageURL" class="form-control" />
							<span asp-validation-for="ImageURL" class="text-danger"></span>
						</div>
					</div>
					<div class="col-md-6">
						<div class="mb-2">
							<label asp-for="CinemaID" class="control-label"></label>
							<select asp-for="CinemaID" class="form-control" asp-items="ViewBag.Cinemas">
								<option></option>
							</select>
							<span asp-validation-for="CinemaID" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="MovieCategory" class="control-label"></label>
							<select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()">
								<option></option>
							</select>
							<span asp-validation-for="MovieCategory" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="ProdcerID" class="control-label"></label>
							<select asp-for="ProdcerID" class="form-control" asp-items="ViewBag.Producers">
								<option></option>
							</select>
							<span asp-validation-for="ProdcerID" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="ActorIDs" class="control-label"></label>
							<select asp-for="ActorIDs" class="form-control" multiple asp-items="ViewBag.Actors"></select>
							<span asp-validation-for="ActorIDs" class="text-danger"></span>
						</div>
					</div>
					<div class="col-md-12">
						<div class="mb-2">
							<label asp-for="Description" class="control-label"></label>
							<textarea asp-for="Description" class="form-control"></textarea>
							<span asp-validation-for="Description" class="text-danger"></span>
						</div>
					</div>
				</div>

				<div class="col-md-4 offset-4 text-center">
					<img width="100%" id="ImagePreview" />
				</div>
				<div class="d-flex justify-content-between mt-3">
					<a asp-action="Index" class="btn btn-outline-secondary">Show All</a>
					<input type="submit" value="Create" class="btn btn-outline-success" />
				</div>
			</form>

		</div>
	</div>
</div>
@section Scripts
{
	<script>
		$(document).ready(function () {
			var output = document.getElementById('ImagePreview');
			output.src = $("#ImageURL").val();
		})
		$("#ImageURL").on("change", function () {
			var output = document.getElementById('ImagePreview');
			output.src = $(this).val();
		})
	</script>
}

Views/Movies/Create.cshtml
@using eTickets.Data.DTOs;
@using eTickets.Data.Enum;
@using eTickets.Data.ViewModels

@model MovieVM


@{
	ViewData["Tittle"] = "Create a new movie";
}

<div class="row">
	<div class="col-md-8 offset-2">
		<p>
			<h4>Create a new movie</h4>
		</p>
	</div>
	<div class="row">
		<div class="col-md-8 offset-2">
			<form asp-action="Create">
				<div class="row">
					<div class="col-md-6">
						<div class="mb-2">
							<label asp-for="Name" class="control-label"></label>
							<input asp-for="Name" class="form-control"/>
							<span asp-validation-for="Name" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="StartDate" class="control-label"></label>
							<input asp-for="StartDate" type="date" class="form-control" />
							<span asp-validation-for="StartDate" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="EndDate" class="control-label"></label>
							<input asp-for="EndDate" type="date" class="form-control" />
							<span asp-validation-for="EndDate" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="Price" class="control-label"></label>
							<input asp-for="Price" type="number" class="form-control" />
							<span asp-validation-for="Price" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="ImageURL" class="control-label"></label>
							<input asp-for="ImageURL" class="form-control" />
							<span asp-validation-for="ImageURL" class="text-danger"></span>
						</div>
					</div>
					<div class="col-md-6">
						<div class="mb-2">
							<label asp-for="CinemaID" class="control-label"></label>
							<select asp-for="CinemaID" class="form-control" asp-items="ViewBag.Cinemas">
								<option></option>
							</select>
							<span asp-validation-for="CinemaID" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="MovieCategory" class="control-label"></label>
							<select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()">
								<option></option>
							</select>
							<span asp-validation-for="MovieCategory" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="ProdcerID" class="control-label"></label>
							<select asp-for="ProdcerID" class="form-control" asp-items="ViewBag.Producers">
								<option></option>
							</select>
							<span asp-validation-for="ProdcerID" class="text-danger"></span>
						</div>
						<div class="mb-2">
							<label asp-for="ActorIDs" class="control-label"></label>
							<select asp-for="ActorIDs" class="form-control" multiple asp-items="ViewBag.Actors"></select>
							<span asp-validation-for="ActorIDs" class="text-danger"></span>
						</div>
					</div>
					<div class="col-md-12">
						<div class="mb-2">
							<label asp-for="Description" class="control-label"></label>
							<textarea asp-for="Description" class="form-control"></textarea>
							<span asp-validation-for="Description" class="text-danger"></span>
						</div>
					</div>
				</div>

				<div class="col-md-4 offset-4 text-center">
					<img width="100%" id="ImagePreview" />
				</div>
				<div class="d-flex justify-content-between mt-3">
					<a asp-action="Index" class="btn btn-outline-secondary">Show All</a>
					<input type="submit" value="Create" class="btn btn-outline-success" />
				</div>
			</form>

		</div>
	</div>
</div>
@section Scripts
{
	<script>
		$(document).ready(function () {
			var output = document.getElementById('ImagePreview');
			output.src = $("#ImageURL").val();
		})
		$("#ImageURL").on("change", function () {
			var output = document.getElementById('ImagePreview');
			output.src = $(this).val();
		})
	</script>
}

Views/Movies/Details.cshtml
@model Movie

@{
    ViewData["Title"] = "Movie details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.CinemaID">
                                @Model.Cinema.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProdcerID">
                                @Model.Producer.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var actor in Model.Actors_Movies)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureURL" style="max-width: 120px" />
                                        <br />
                                        <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.ActorID">@actor.Actor.FullName</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text d-flex justify-content-between">
                            <a class="btn btn-success text-white  @((DateTime.Now > Model.EndDate) ? "disabled" : "")"
                               asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@Model.ID">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))
                            </a>
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Movies/Index.cshtml
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "Movies";
}

<div class="row p-1">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <div class="card-text">
                                <h5 class="card-title d-flex justify-content-between">
                                    @item.Name
                                    @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a asp-action="Edit" asp-route-id="@item.ID" class="text-white float-right"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b> @item.Cinema.Name</p>
                            <p class="card-text"><b>Category: </b>@item.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if(DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success">AVAILABLE</span>
                                }
                                else if(DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary">UPCOING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text align-content-between d-flex justify-content-between">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.ID" >
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.ID">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                 </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "Movies");